import operator
from typing import TypedDict, List, Annotated, Dict, Any

class AgentState(TypedDict):
    """
    Represents the internal state of the graph.
    
    Attributes:
        task (str): The initial user request.
        plan (List[str]): The research plan steps generated by the Planner.
        research_notes (List[str]): Accumulated findings. Uses operator.add to append, not overwrite.
        draft (str): The generated email/report.
        critique (str): Feedback from the Verifier.
        revision_number (int): Tracks loops to prevent infinite refinement.
        max_revisions (int): Hard limit on loops (default 2).
        logs (List[dict]): Traceability for the UI. Format: {"agent": str, "message": str}
        metrics (List[dict]): Store observability data. Format: {"metric": str, "value": Any}
        is_safe (bool): Flag for security status.
    """
    task: str
    plan: List[str]
    research_notes: Annotated[List[str], operator.add]
    draft: str
    critique: str
    revision_number: int
    max_revisions: int
    logs: Annotated[List[Dict[str, Any]], operator.add]
    metrics: Annotated[List[Dict[str, Any]], operator.add]
    is_safe: bool
